// The report page is the one-click surface, so its data has to be current and
// its promises have to hold. A page that quietly renders last week's numbers is
// worse than no page.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const read = (/** @type {string[]} */ ...p) => fs.readFileSync(path.join(ROOT, ...p), 'utf8');

test('the committed report and the page data are not stale', () => {
  const r = spawnSync(process.execPath, [path.join(ROOT, 'tools', 'build-report.mjs'), '--check'], {
    encoding: 'utf8', windowsHide: true, timeout: 300000,
  });
  assert.equal(r.status, 0, (r.stdout ?? '') + (r.stderr ?? ''));
});

test('data.js is a classic script that only assigns, so the page opens from file://', () => {
  const data = read('web', 'data.js');
  assert.match(data, /^\/\/ Generated by tools\/build-report\.mjs/);
  assert.match(data, /window\.COFFERDAM = \{/);
  assert.ok(!/\bimport\b|\bexport\b|\brequire\(/.test(data), 'module syntax would not load from file://');
});

test('the page carries a real corruption, with a diff, on its default view', () => {
  const data = read('web', 'data.js');
  const json = JSON.parse(data.slice(data.indexOf('{'), data.lastIndexOf(';')));
  const first = json.views[0];
  assert.ok(first.corrupt > 0, 'the default view must open on a failure, not a green wall');
  assert.ok(first.firstFinding, 'the default view must carry the finding it opens on');
  assert.ok(first.firstFinding.diff.length > 0, 'a corruption with no diff explains nothing');
  assert.ok(first.firstFinding.expected.length + first.firstFinding.got.length > 0);
  const withFinding = first.points.filter((/** @type {any} */ p) => p.f);
  assert.ok(withFinding.length > 0);
  // At least one view must be all-green, or the page never shows what correct
  // looks like.
  assert.ok(json.views.some((/** @type {any} */ v) => v.corrupt === 0 && v.build === 'correct'));
});

test('every point in every view carries a verdict and a reason when it is not consistent', () => {
  const data = read('web', 'data.js');
  const json = JSON.parse(data.slice(data.indexOf('{'), data.lastIndexOf(';')));
  for (const view of json.views) {
    assert.equal(view.points.length, view.crashPoints);
    let c = 0, x = 0, u = 0;
    for (const p of view.points) {
      assert.ok(['c', 'x', 'u'].includes(p.v), 'unknown verdict ' + p.v);
      if (p.v === 'c') c++; else if (p.v === 'x') x++; else u++;
      if (p.v !== 'c') assert.ok(p.r && p.r.length > 10, 'crash point ' + p.i + ' has no stated reason');
      assert.ok(typeof p.op === 'string' && p.op.length > 0);
    }
    assert.deepEqual([c, x, u], [view.consistent, view.corrupt, view.unverifiable]);
  }
});

test('the page names its prior art on the first screen', () => {
  const html = read('web', 'index.html');
  const firstScreen = html.slice(0, html.indexOf('id="verdict"'));
  assert.match(firstScreen, /CrashMonkey/);
  assert.match(firstScreen, /ALICE/);
  assert.match(firstScreen, /OSDI/);
});

test('the page states its three outcomes and its scope cuts', () => {
  const html = read('web', 'index.html');
  for (const word of ['consistent', 'corrupt', 'unverifiable']) assert.match(html, new RegExp(word));
  assert.match(html, /Not a database/);
  assert.match(html, /Single process, single writer/);
});

test('the page is self-contained: no server, no network, no build step at view time', () => {
  const html = read('web', 'index.html');
  assert.ok(!/src="https?:\/\//.test(html));
  assert.ok(!/href="https?:\/\/[^"]*\.css/.test(html));
  const app = read('web', 'app.js');
  assert.ok(!/\bfetch\s*\(/.test(app));
  assert.ok(!/XMLHttpRequest/.test(app));
});

test('the report the page renders is the report the CLI can re-run', () => {
  const committed = JSON.parse(read('crashes.json'));
  const data = read('web', 'data.js');
  const rendered = JSON.parse(data.slice(data.indexOf('{'), data.lastIndexOf(';')));
  assert.deepEqual(rendered.control, committed.control);
  assert.deepEqual(rendered.fixtures, committed.fixtures);
  assert.deepEqual(rendered.bounds, committed.bounds);
});
